name: Build SPFx Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build SPFx solution bundle
      run: gulp bundle --ship

    - name: Build SPFx solution package-solution
      run: gulp package-solution --ship
      
    - name: Upload .sppkg file
      uses: actions/upload-artifact@v2
      with:
        name: sppkg
        path: sharepoint/solution/*.sppkg
